theme: jekyll-theme-cayman
title: 王鑫的简历
description: 你可以在这里我的全部信息
github:
  is_project_page: true
  repository_url: https://github.com/xinyer/xinyer.github.io
  repository_name: xinyer.github.io
  owner_url: https://github.com/xinyer
  owner_name: xinyer
  
markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
