theme: jekyll-theme-cayman
title: Xin's blogs
description: READING, WRITING, FIND ME
github:
  is_project_page: true
  repository_url: https://github.com/xinyer/xinyer.github.io
  repository_name: xinyer.github.io
  owner_url: https://github.com/xinyer
  owner_name: xinyer
  
markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
